### ISSUE TITLE
Various tools import the `chemistry` module; what is it?

### ISSUE THREAD

**Issue by davidlmobley** [choderalab/LiquidBenchmark#66]
I've successfully used what's here to repeat the calculations with a different forcefield, for comparison, and am at the point of analysis. However, I find that the tool `munge_output_amber.py` (and several other scripts) imports the `chemistry` module. What is this module?

(Update: After some Googling of the usage `load_file` in the context of an AMBER parameter file, I'm thinking maybe this was an old version of `parmed`. Is that correct, @kyleabeauchamp ?)

**Comment by kyleabeauchamp** [comment]
Indeed.  I tracked down the parmed changes here:

https://github.com/ParmEd/ParmEd/pull/173

**Comment by davidlmobley** [comment]
Thanks.
