### ISSUE TITLE
Bootstrapping analysis - need some help

### ISSUE THREAD

**Issue by davidlmobley** [choderalab/LiquidBenchmark#67]
I'm analyzing some calculations I ran with this (but with a different forcefield) to compare with your work, @kyleabeauchamp . However, I've run into issues with this bit of code around line 143 of `plot_tbv.py`:

```
x, y = pred["density"], pred["expt_density"]
relative_rms = (((x - y) / x)**2).mean()** 0.5
cv = sklearn.cross_validation.Bootstrap(len(x), train_size=len(x) - 1, n_iter=100)
relative_rms_grid = np.array([(((x[ind] - y[ind]) / x[ind])**2).mean()** 0.5 for ind, _ in cv])
```

scikit-learn no longer contains a `Bootstrap` function, nor is it clear to me which version of scikit-learn you used (the function worked somewhat differently in different versions of scikit-learn). Without comments, I'm having a bit of trouble interpreting what the `cv` and `relative_rms_grid` lines are exactly supposed to do/finding a replacement.

@kyleabeauchamp - any chance you could provide a quick replacement for the Bootstrap line or explain your target end product here and how you were obtaining it? I'm very much hoping to generate plots which match what you did (aside from differing in what force field I used!) but I'm beating my head against this.

**Comment by davidlmobley** [comment]
Actually, it doesn't look like that code is actually USED for anything, oddly. Specifically, `relative_rms_grid` is calculated but never used... So I can apparently proceed by just commenting it out !!?!

**Comment by kyleabeauchamp** [comment]
I agree with this interpretation: looks like the main use of this was to get bootstrap estimates on RMS error, which didn't end up getting used in the figure code below.

**Comment by kyleabeauchamp** [comment]
I believe the version of Bootstrap in sklearn 0.16.0 should do the trick (linked below).  I would need double check, however, but for the time being you now have two options.  

https://github.com/scikit-learn/scikit-learn/blob/df9f90cfa8795b6d85056f70177fb783d6ecafda/sklearn/cross_validation.py#L613

**Comment by davidlmobley** [comment]
Thanks, Kyle.
