### ISSUE TITLE
Where to get chemistry module?

### ISSUE THREAD

**Issue by ocmadin** [choderalab/LiquidBenchmark#68]
I am attempting to calculate dielectric constants via the method in `munge_output_amber.py`, but can't find the required `chemistry` module imported in the first line of that code.  Is that module publicly available somewhere?

**Comment by kyleabeauchamp** [comment]
Iirc that's an old version of parmed.

**Comment by ocmadin** [comment]
Ahhhhhh, thanks.  I appreciate it!
